# Generated by Django 3.0.7 on 2020-06-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookflix', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
