# Generated by Django 3.0.7 on 2020-06-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBookflix', '0003_auto_20200615_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_libros'),
        ),
    ]
